using System.Collections.Generic;

public static class StatLabels
{
    public static readonly Dictionary<StatType, string> Labels = new Dictionary<StatType, string>
    {
        {
            StatType.FireRate,
            "fire_rate_label"
        },
        {
            StatType.ReloadRate,
            "reload_rate_label"
        },
        {
            StatType.LifeTime,
            "lifetime_label"
        },
        {
            StatType.BulletDamage,
            "bullet_damage_label"
        },
        {
            StatType.SummonDamage,
            "summon_damage_label"
        },
        {
            StatType.SummonAttackSpeed,
            "summon_attack_speed_label"
        },
        {
            StatType.Projectiles,
            "projectiles_label"
        },
        {
            StatType.ProjectileSpeed,
            "projectile_speed_label"
        },
        {
            StatType.ProjectileSize,
            "projectile_size_label"
        },
        {
            StatType.Knockback,
            "knockback_label"
        },
        {
            StatType.Red,
            "red_label"
        },
        {
            StatType.Yellow,
            "yellow_label"
        },
        {
            StatType.Spread,
            "spread_label"
        },
        {
            StatType.Bounce,
            "bounce_label"
        },
        {
            StatType.Piercing,
            "piercing_label"
        },
        {
            StatType.Blue,
            "blue_label"
        },
        {
            StatType.ManaRegen,
            "mana_regen_label"
        },
        {
            StatType.PickupRange,
            "pickup_range_label"
        },
        {
            StatType.VisionRange,
            "vision_range_label"
        },
        {
            StatType.Dodge,
            "dodge_label"
        },
        {
            StatType.DodgeCapMod,
            "dodge_cap_label"
        }
    };
}